デザインは完成しました。
KDG-Develop-Hub/social-web pull request #16
Opened 2024-06-14 13:20 UTC by okamuratakeru

## 対応したこと

ある程度のデザイン完成

## 対応 Issue

綴るためのダイアログの実装 #7
https://github.com/KDG-Develop-Hub/social-web/issues/7

## 関連資料

## 残タスク

## 画面キャプチャ
<img width="1543" alt="スクリーンショット 2024-06-14 22 19 44" src="https://github.com/KDG-Develop-Hub/social-web/assets/79039357/313c1447-657d-4921-953d-3cf66a8757da">

2024-06-15 14:29 UTC, imeankenshin requested changes
ご対応ありがとうございます！
ニッチながらもスタイル修正をお願いしたい🙏
![image](https://github.com/KDG-Develop-Hub/social-web/assets/103516503/d81816a7-a005-4a21-a744-b75a00b8db1c)

2024-06-16 01:58 UTC, okamuratakeru commented
> よろしくお願いいたします！ ニッチながらもスタイル修正をお願いしたい🙏 ![画像](https://private-user-images.githubusercontent.com/103516503/339996676-d81816a7-a005-4a21-a744-b75a00b8db1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MDMzMDMsIm5iZiI6MTcxODUwMzAwMywicGF0aCI6Ii8xMDM1MTY1MDMvMzM5OTk2Njc2LWQ4MTgxNmE3LWEwMDUtNGEyMS1hNzQ0LWI3NWEwMGI4ZGIxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwMTU2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2U5NDgzMmFiODI3MjhjOGVlZDcwZWM1MDUzMTBlMDQwZWQ0YTY2ZGJiNjRiMTYzN2E0M2ZhZGE1NGVkNzVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.etwCeaLzXi6fwYBTnjK0TjXBk6laR61V1faosSdK2Dg)

了解です！直しますー

2024-06-19 01:41 UTC, okamuratakeru commented on components/material/Button.vue
https://github.com/KDG-Develop-Hub/social-web/assets/79039357/abbc911f-6c7f-44a9-8b35-9094f1d03665

デザインです

2024-06-19 07:40 UTC, imeankenshin approved these changes
LGTM!無効化するためのプロパティがButtonに設定されてないが、これは自分の方で対応しとくぜえい💪

2024-06-19 07:41 UTC, merged