Feature/error
KDG-Develop-Hub/social-web pull request #33
Opened 2024-09-18 09:20 UTC by minoru-kinugasa-105

## 対応したこと

- 404ページの作成
   - `[...slug].vue`にあった簡易404コードを`/404`に推移するように変更
- 500ページの作成
  - `pulgins/`にエラーハンドリングするためのコードを実装
- global.cssの編集
  - box-sizing: border-boxを全ての要素に適用させるように変更

## 対応 Issue
- #26 

## 関連資料
デザイン: https://www.figma.com/design/feJkoD1AFJ6NXsBEQ5xqF9/app?node-id=1336-5174&node-type=SECTION&t=K8JIgZytHHgc37gi-11

## 残タスク
なし

## 画面キャプチャ
<img width="1702" alt="image" src="https://github.com/user-attachments/assets/1786176d-c82a-442a-a08a-3fc3a627ee19">
<img width="1701" alt="image" src="https://github.com/user-attachments/assets/11e2071a-dd40-4717-948e-3affc2761a96">

2024-09-18 09:36 UTC, imeankenshin commented
LGTM!丁寧に実装されてそんなに悪い点はなかったかな。一点だけ修正して欲しいところあるのでよろしく〜

2024-09-18 09:48 UTC, okamuratakeru commented
あ、ごめんNuxtの機能でルーティングされるからいいのか？
ごめん頭回ってないわ

2024-09-18 09:57 UTC, imeankenshin requested changes
幾らか修正点あるので対応お願い🙇‍♂️

2024-09-18 09:57 UTC, imeankenshin commented on pages/404.vue
> +    <div class="error-container">
この文章はそれぞれ、手動で設定せずにこのクラスを使ってください！これを使うと、ちょうど全く同じなスタイルが割り当てられるので！
```
error-emoticon    -> display-lg
error-title       -> display-md
error-description -> body-md
```

2024-09-18 09:57 UTC, imeankenshin commented on pages/[...slug].vue
> -<script setup>
404ページにプッシュするって形だとページ遷移履歴に残っちゃったりするから、このページにNot foundページを実装した方がいいね！
`[...slug].vue`だと確かにわかりにくいから、`[...404].vue`にした方がいいね。これは僕のミス申し訳ない🙏

2024-09-18 09:57 UTC, imeankenshin commented on pages/500.vue
> +    </p>
404.vue同様、用意されてるクラスを使ってね！ありがとう

2024-09-18 09:57 UTC, imeankenshin commented on pages/500.vue
pluginsを使いこなしてるのはいいね！結構感動した。
500ページは`error.vue`を利用する方が完結に済むと思うから、そっちがいいかな？お願いします！

2024-09-18 11:05 UTC, minoru-kinugasa-105 commented
> 幾らか修正点あるので対応お願い🙇‍♂️

修正しました！
commit時のメッセージが多くて、txtファイルにまとめたらミスで反映されなかったので、ここに記述します！

- 500ページのファイル名を`error.vue`に修正
- 404ページの推移方法を`push`から`navigateTo`メソッドに修正
- 500, 404ページで使用しているスタイルを既存のものを使うように修正

2024-09-21 06:24 UTC, imeankenshin approved these changes
LGTM!

2024-09-21 06:25 UTC, imeankenshin commented
displayのクラス作るの忘れてたから、こちらが作成しとくね。

2024-09-21 06:47 UTC, merged