Firebaseとの統合の準備と、レイアウト改善
KDG-Develop-Hub/social-web pull request #49
Opened 2024-11-29 07:06 UTC by imeankenshin

## 対応したこと

- Vuefireを用いた、Firebaserとの統合に関する設定
- ホーム画面にて、投稿一覧を取得して表示する実装
- プロフィール画面にて、投稿一覧を取得して表示する実装
- 取得中のロード画面を適切に表示させるために、レイアウトを改善。

## 対応 Issue

- close #47 
- close #48 

## 関連資料

- Vuefireについて: https://vuefire.vuejs.org/guide/getting-started.html

## 残タスク

- プロフィール画面にて、投稿一覧を取得して表示する実装。複合クエリが使えず完成できない。

## 画面キャプチャ

<img width="1512" alt="Screenshot 2024-11-29 at 16 04 32" src="https://github.com/user-attachments/assets/107afb1e-8d19-4a62-82d5-6d766453d7fb">

https://github.com/user-attachments/assets/6ece632f-5cce-44e4-964e-0c2a13babd9c

2024-11-29 09:13 UTC, Haru-Kobayashi073 requested changes
Firebaseの環境分け待ってます！

2024-12-01 03:04 UTC, imeankenshin commented
@Haru-Kobayashi073 環境分けできました！！！！！！！

2024-12-07 07:57 UTC, Haru-Kobayashi073 approved these changes
LGTM!

2024-12-14 09:02 UTC, imeankenshin commented
実装に問題ないと判断し、このままマージしちゃいます！

2024-12-14 09:02 UTC, merged